package com.siberhus.mailberry.dao.hsql;

import java.util.Properties;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import com.siberhus.mailberry.dao.AbstractTrackingDaoTest;
import com.siberhus.mailberry.dao.TrackingDao;
import com.siberhus.mailberry.dao.impl.hsql.TrackingDaoImpl;

public class HsqlTrackingDaoTest extends AbstractTrackingDaoTest{
	
	@Override
	public TrackingDao getTrackingDao() {
		
		EntityManagerFactory emf = Persistence.createEntityManagerFactory(
				"mailberry_hsqldb", new Properties());
		
//		DriverManagerDataSource dataSource = new DriverManagerDataSource(){
		SingleConnectionDataSource dataSource = new SingleConnectionDataSource();
		dataSource.setDriverClassName("org.hsqldb.jdbcDriver");
		dataSource.setUrl("jdbc:hsqldb:mem:test");
		dataSource.setUsername("sa");
		dataSource.setPassword("");
		NamedParameterJdbcTemplate jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
		TrackingDaoImpl trackingDao = new TrackingDaoImpl();
		trackingDao.setNamedParameterJdbcTemplate(jdbcTemplate);
		trackingDao.setEntityManager(emf.createEntityManager());
		
//		jdbcTemplate.getJdbcOperations().execute("CREATE TABLE IF NOT EXISTS clickstreams (" +
//			"id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, campaign_id BIGINT NOT NULL,click_count INT)");
		
		return trackingDao;
	}
	
}
